### ISSUE TITLE
Don't allow to enter the full credit card in the field, only the last 4 digits

### ISSUE THREAD

**Issue by glrodasz** [glrodasz/sublr#5]

**Comment by ntoniocp** [comment]
Hey I would like to add this feature. Could you assign it to me please? 

Also I wanted to ask: The expected behavior is that the user only could type only 4 digits in the input? Should it show some message? or just the limitation of the input it's okay?

**Comment by glrodasz** [comment]
@ntoniocp done!

**Comment by ntoniocp** [comment]
Thanks, I just made the PR!
