### ISSUE TITLE
Add an skeleton loader for the body of the app

### ISSUE THREAD

**Issue by glrodasz** [glrodasz/sublr#6]
This is an example of the possible skeleton structure, consider to add the shimmer effect as well: https://codepen.io/JCLee/pen/dyPejGV

![image](https://user-images.githubusercontent.com/1431663/196555006-af0ec98a-1e2a-4652-a0c6-9c76edf0d338.png)

**Comment by ntoniocp** [comment]
Hey I would like to take this one please assign it to me
